### PR TITLE
Add CI for Plone 5.0-6.0, restore background image css

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Note: I would be happy to drop 5.0 and 5.1 support.
And since the latest release supports 5.2, I would be fine with dropping Python 2 support as well.
But we can keep it.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
I have added GitHub Actions, using the new [`collective/tox-action`](https://github.com/collective/tox-action) I created yesterday. Locally tox runs fine, but here on GitHub the actions are not running. This may be because I do not have the right permissions on this repo. Or maybe someone needs to enable actions in the settings.

@cekk, could you review, or assign this to someone else?

**Review by cekk — APPROVED** [review]

**Comment by cekk** [comment]
probably it depends on a default setting in the repo actions:

> Require approval for first-time contributors
> Only first-time contributors will require approval to run workflows.
> 
And you are a first-time contributor here.

I approved the pr but tests didn't started. Anyway i can try to merge it and see if actions starts.
The code LGTM but i will keep python2 compat because we're still using that portlet on old sites.

**Comment by mauritsvanrees** [comment]
Apparently there should be an "Approve and run" button.
See https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Comment by cekk** [comment]
ok, i merged it and the ci started working..now we have a failing test for plone52-py27

**Comment by mauritsvanrees** [comment]
Could you make a release please?

**Comment by cekk** [comment]
done!

**Pull request merged**
